# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-26 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edtech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='diagram',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='hints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='test_series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='edtech.TestSeries'),
        ),
    ]
