# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-26 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edtech', '0002_auto_20181226_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='edtech.Question'),
        ),
    ]
