# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-27 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edtech', '0003_auto_20181226_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionanswer',
            name='session_end',
            field=models.BooleanField(default=False),
        ),
    ]
