# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-10 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edtech', '0004_userquestionanswer_session_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='type',
            field=models.CharField(choices=[(b'Image', b'Image'), (b'Text', b'Text')], default=b'Text', max_length=100),
        ),
    ]
