# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-16 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edtech', '0006_auto_20190316_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.CharField(max_length=10000),
        ),
    ]
