# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-17 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edtech', '0007_auto_20190316_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionanswer',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edtech.Choice'),
        ),
    ]
